### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by Krosta8** [Ordinastie/MalisisAdvert#1]
Hello,
I'm writting here, because it is better, like you wrote, that sometimes you can't see a mesage on Curse.

Could you add a version of Billboard without a stand? Because I would like to put it on the wall (panel is too small for my purpose).
About Billboard another question.
Could you add an option to vanish the platform?

**Comment by Ordinastie** [comment]
I might consider it, but don't hold your breath over it. It would be very low on my proirity list as I have so many things to do already.

**Comment by Krosta8** [comment]
Okay, thank you :)
